[versions]
encoding = "1.2.3"
vcLib = "4.0.0"
mdl = "1.0.0"
kmpCrypto = "3.5.0"
ida = "3.8.1"
eupid = "2.1.1"
powerofrepresentation = "1.0.0"
certificateofresidence = "1.0.0"
atomicfu = "0.23.2"
compose-plugin = "1.6.11"
kotlin = "2.0.0"


[libraries]
base16 = { group = "io.matthewnelson.kotlin-components", name = "encoding-base16", version.ref = "encoding" }
base64 = { group = "io.matthewnelson.kotlin-components", name = "encoding-base64", version.ref = "encoding" }
vclib = { group = "at.asitplus.wallet", name = "vclib", version.ref = "vcLib" }
kmpCrypto = { group = "at.asitplus.crypto", name = "datatypes", version.ref = "kmpCrypto" }
kmpCrypto-jws = { group = "at.asitplus.crypto", name = "datatypes-jws", version.ref = "kmpCrypto" }
kmpCrypto-cose = { group = "at.asitplus.crypto", name = "datatypes-cose", version.ref = "kmpCrypto" }
credential-ida = { module = "at.asitplus.wallet:idacredential", version.ref = "ida" }
credential-eupid = { module = "at.asitplus.wallet:eupidcredential", version.ref = "eupid" }
credential-powerofrepresentation = { module = "at.asitplus.wallet:powerofrepresentation", version.ref = "powerofrepresentation" }
credential-certificateofresidence = { module = "at.asitplus.wallet:certificateofresidence", version.ref = "certificateofresidence" }

atomicfu = { group = "org.jetbrains.kotlinx", name = "atomicfu", version.ref = "atomicfu" }
vclib-openid = { group = "at.asitplus.wallet", name = "vclib-openid", version.ref = "vcLib" }
vclib-mdl = { group = "at.asitplus.wallet", name = "mobiledrivinglicence", version.ref = "mdl" }

[plugins]
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }