[versions]
encoding = "1.2.3"
vck = "5.0.0-SNAPSHOT"
mdl = "1.1.0-SNAPSHOT"
ida = "3.9.0"
eupid = "2.2.0-SNAPSHOT"
powerofrepresentation = "1.1.0"
certificateofresidence = "2.1.0"
eprescription = "1.0.1"
atomicfu = "0.23.2"
compose-plugin = "1.6.11"
kotlin = "2.0.20"


[libraries]
vck = { group = "at.asitplus.wallet", name = "vck", version.ref = "vck" }
vck-openid = { group = "at.asitplus.wallet", name = "vclib-openid", version.ref = "vck" }
atomicfu = { group = "org.jetbrains.kotlinx", name = "atomicfu", version.ref = "atomicfu" }
credential-ida = { module = "at.asitplus.wallet:idacredential", version.ref = "ida" }
credential-eupid = { module = "at.asitplus.wallet:eupidcredential", version.ref = "eupid" }
credential-powerofrepresentation = { module = "at.asitplus.wallet:powerofrepresentation", version.ref = "powerofrepresentation" }
credential-certificateofresidence = { module = "at.asitplus.wallet:certificateofresidence", version.ref = "certificateofresidence" }
credential-mdl = { group = "at.asitplus.wallet", name = "mobiledrivinglicence", version.ref = "mdl" }
credential-eprescription = { module = "at.asitplus.wallet:eprescription", version.ref = "eprescription"}

[plugins]
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
